name: Build Jekyll site

on:
  push:
    branches:
      - main # or master before October 2020

jobs:
  buildsite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.BUILD_TOKEN }}
